#!/usr/bin/env python

import sys, getopt, socket, time, os, imp

sys.path.append('dataparsers/')
from database import Database
from amp import insert_amp_streams
from rrd import insert_rrd_streams

def import_modules(path):
    modules = {}
    for i in os.listdir(path):
        if i.endswith('.py'):
            name = i[:-3]
            modules[name] = imp.load_source(name, os.path.join(path,i))
    return modules       
 
modules = import_modules('dataparsers/')

db = Database("ntsc2", "salcock", "", "", debug=False)
db.build_databases(modules, new=True)

insert_amp_streams(db, "amp.conf")
insert_rrd_streams(db, "rrd.conf")
# vim: set sw=4 tabstop=4 softtabstop=4 expandtab :

