#!/bin/sh

PATH=/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/nntsc
NAME=nntsc
PIDFILE=/tmp/nntsc.pid
CONF=/etc/nntsc.conf

export PATH=$PATH

test -f $CONF || exit 0
test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
  	echo "Starting $NAME"
	start-stop-daemon --quiet --start --exec $DAEMON \
		-- -P $PIDFILE -C $CONF -b
	
	if [ $? -ne 0 ]; then
		echo "Failed to start $NAME"
	else
		echo "Started"
	fi
	;;
  stop)
  	echo "Stopping $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
	echo "Stopped"
	;;
  restart)
  	echo "Restarting $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
	echo "Stopped"
	sleep 1
	start-stop-daemon --start --quiet --exec $DAEMON \
		-- -P $PIDFILE -C $CONF -b
	echo "Restarted"
	;;
  *)
  	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0

	

