#!/bin/sh
### BEGIN INIT INFO
# Provides:          nntsc
# Required-Start:    $remote_fs $network $local_fs
# Required-Stop:     $remote_fs $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NNTSC data collector
# Description:       NNTSC data collector
### END INIT INFO

PATH=/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/nntsc
NAME=nntsc
USER=""     # Change this in /etc/default/nntsc
GROUP=""    # Change this in /etc/default/nntsc

# These should get overridden by the contents of /etc/default/nntsc
CONF=/etc/nntsc/nntsc.conf
PIDFILE=/tmp/nntsc.pid

export PATH=$PATH

if test -f /etc/default/nntsc; then
	. /etc/default/nntsc
fi

test -f $CONF || exit 0
test -x $DAEMON || exit 0

# quick attempt to make sure people actually look at the config file
if [ ! "$START_DAEMON" -gt 0 ]; then
    echo 'Not starting nntsc: edit config in /etc/nntsc/nntsc.conf and' >&2
    echo 'enable the daemon in /etc/default/nntsc' >&2
    exit 0
fi

set -e

case "$1" in
  start)
  	echo "Starting $NAME"
	start-stop-daemon --quiet --start --chuid $USER:$GROUP --exec $DAEMON \
		-- -P $PIDFILE -C $CONF -b

	if [ $? -ne 0 ]; then
		echo "Failed to start $NAME"
	else
		echo "Started"
	fi
	;;
  stop)
  	echo "Stopping $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
	echo "Stopped"
	;;
  restart|force-reload)
  	echo "Restarting $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
	echo "Stopped"
	sleep 1
	start-stop-daemon --start --quiet --exec $DAEMON \
		-- -P $PIDFILE -C $CONF -b
	echo "Restarted"
	;;
  *)
  	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0


