#!/bin/sh
# postinst script for #PACKAGE#
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

create_dummy_columns()
{
    if [ $# -ne 1 ]; then
        echo "create_dummy_columns expects 1 argument, $# given"
        return
    fi

    # add an extra field that won't be null to satisfy some
    # influxdb issues that unfortunately need to match in postgres
    su postgres -c "psql -q -c \
        \"DO \
        \\$\\$ \
        DECLARE \
            row record; \
        BEGIN \
            FOR row in SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE '$1%' \
            LOOP \
                BEGIN \
                    EXECUTE 'ALTER TABLE public.' || quote_ident(row.tablename) || ' ADD COLUMN unused boolean NOT NULL DEFAULT TRUE;'; \
                EXCEPTION \
                    WHEN duplicate_column THEN \
                        NULL; \
                END; \
            END LOOP; \
        END; \
        \\$\\$;\" -d nntsc"
}

relax_null_constraint()
{
    if [ $# -ne 2 ]; then
        echo "relax_null_constraint expects 2 arguments, $# given"
        return
    fi

    table=$1
    column=$2

    su postgres -c "psql -q -c \
        \"DO \
        \\$\\$ \
        DECLARE \
            row record; \
        BEGIN \
            FOR row in SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE '$table%' \
            LOOP \
                EXECUTE 'ALTER TABLE public.' || quote_ident(row.tablename) || ' ALTER COLUMN $column DROP NOT NULL;'; \
            END LOOP; \
        END; \
        \\$\\$;\" -d nntsc"
}


case "$1" in
    configure)
        CONF=/etc/nntsc/nntsc.conf

        if [ `lsb_release -c -s` = "wheezy" ]; then
            echo "============================================================"
            echo "Debian Wheezy has old python packages, run:"
            echo
            echo "  sudo pip install --upgrade pika"
            echo "============================================================"
        fi

        # ensure the cuz system user exists
        if ! getent passwd cuz > /dev/null; then
            adduser --quiet --system --group --no-create-home cuz
        fi

        # ensure the cuz database user exists
        su postgres -c "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='cuz'\" | grep -q 1 || createuser cuz"

        # ensure the nntsc database exists
        su postgres -c "psql --list | cut -d ' ' -f 2 | grep -qx nntsc || \
            createdb -O cuz nntsc"

        # apply the schema and config to the nntsc database
        su cuz -s /bin/bash -c "build_nntsc_db -C $CONF"

        # ensure the nntsc rabbitmq user exists and the password matches the
        # configuration file
        PASSWD=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1`
        /usr/sbin/rabbitmqctl list_users | cut -f 1 | grep -qx nntsc || \
            (/usr/sbin/rabbitmqctl add_user nntsc $PASSWD && \
             /usr/sbin/rabbitmqctl set_permissions nntsc ".*" ".*" ".*" && \
             sed -i "s/username = guest/username = nntsc/" $CONF && \
             sed -i "s/password = guest/password = $PASSWD/" $CONF)

        if [ -n $2 ]; then
            if dpkg --compare-versions "$2" le-nl "2.11-1"; then
                # add new protocol column and update table constraints
                su postgres -c "psql -q -c \
                    \"ALTER TABLE streams_amp_throughput \
                    ADD COLUMN protocol \
                    VARCHAR NOT NULL DEFAULT 'default'\" -d nntsc || true"

                su postgres -c "psql -q -c \
                    \"ALTER TABLE streams_amp_throughput DROP CONSTRAINT \
                    streams_amp_throughput_source_destination_direction_address_key; \
                    \" -d nntsc || true"

                su postgres -c "psql -q -c \
                    \"ALTER TABLE streams_amp_throughput ADD CONSTRAINT \
                    streams_amp_throughput_source_destination_direction_address_key \
                    UNIQUE (            \
                        source,         \
                        destination,    \
                        direction,      \
                        address,        \
                        duration,       \
                        writesize,      \
                        tcpreused,      \
                        protocol);\" -d nntsc || true"
            fi

            if dpkg --compare-versions "$2" le-nl "2.22-1"; then
                # relax some restrictions that shouldn't apply now that
                # unresolved destinations are included in results. Generally
                # only traceroute data is stored in postgres, but it's still
                # possible to run without influx and store everything here
                relax_null_constraint "data_amp_astraceroute" "addresses"
                relax_null_constraint "data_amp_astraceroute" "errors"

                relax_null_constraint "data_amp_udpstream" "packets_sent"
                relax_null_constraint "data_amp_udpstream" "packets_recvd"
                relax_null_constraint "data_amp_udpstream" "lossrate"

                relax_null_constraint "data_amp_tcpping" "loss"
                relax_null_constraint "data_amp_tcpping" "results"
                relax_null_constraint "data_amp_tcpping" "icmperrors"
                relax_null_constraint "data_amp_tcpping" "lossrate"

                relax_null_constraint "data_amp_icmp" "loss"
                relax_null_constraint "data_amp_icmp" "results"
                relax_null_constraint "data_amp_icmp" "lossrate"

                relax_null_constraint "data_amp_dns" "lossrate"
                relax_null_constraint "data_amp_fastping" "lossrate"

                # add an extra field that won't be null to satisfy some
                # influxdb issues that unfortunately need to match in postgres
                create_dummy_columns "data_amp_throughput"
                create_dummy_columns "data_amp_udpstream"
                create_dummy_columns "data_amp_traceroute_pathlen"
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
